= My Articles

This is a project contains articles or article related materials like source code that are too small to be published as a separate project.
Some of the articles are published only here, other are saved here as they are not easily available in other sources anymore.

If you want to comment on an article, please use https://github.com/const/const-articles/discussions[discussions]. If you found factual or other error, please use https://github.com/const/const-articles/issues[issue tracker].

Also note, that some articles are quite old, so there are changes in my understanding since then.

* link:evolution/README.adoc[Language and System Evolution]

== License

link:LICENSE[MIT License] is applicable to source code in articles, if source code is not quoted from other sources.

link:LICENSE-articles[CC BY-NC-ND License] is applicable to article texts published here (if republished elsewhere, there could be also a separate license). Possibly the license will be weakened later, if there is a need for it.